apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: flow-2
  name: flow-2
spec:
  replicas: 1
  selector:
    matchLabels:
      run: flow-2
  template:
    metadata:
      labels:
        run: flow-2
    spec:
      containers:
      - image: flow-2:create
        name: flow-2
        ports:
        - containerPort: 80
