apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: flow-3
  name: flow-3
spec:
  replicas: 1
  selector:
    matchLabels:
      run: flow-3
  template:
    metadata:
      labels:
        run: flow-3
    spec:
      containers:
      - image: flow-3:create
        name: flow-3
        ports:
        - containerPort: 80

        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: flow-3-volume
      volumes:
      - name: flow-3-volume
        hostPath:
          path: /Users/.minikube-mounts/flow-3
